spring:
  batch:
    job:
      names: ExportMybatisCursorJob
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-postgresql.sql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kakeibo
    username: postgres
    password: postgres
    
# Message
  messages:
    basename: i18n/messages,i18n/ValidationMessages
    fallback-to-system-locale: false
  
# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/example/repository/kakeibo/*.xml
  type-aliases-package: com.example.domain.kakeibo

logging:
  level:
    '[com.example]': debug