@startuml tables
entity kakeibo as "kakeibo\n家計簿" {
  + id [PK]
  --
  user_id [ユーザーID]
  payment_date [支払日]
  expense_item_id [費目ID]
  expenditure_amount [支払金額]
  income_amount　[収入金額]
  payment_id [決済ID]
  used_store [利用店舗]
  remarks [備考]
  insert_at [登録日]
  update_at [更新日]
}
entity users as "users\nユーザー" {
  + id [PK]
  --
  mail_address [メールアドレス]
  password [パスワード]
  name [名前]
  gender [性別]
  date_of_birth [生年月日]
  remarks [備考]
  
}

entity expense_item  as "expense_item \n費目" {
  + id [PK]
  --
  expense_item_name [費目名]
}
entity settlement  as "settlement \n決済" {
  + id [PK]
  --
  settlement_name [決済方法]
}
entity board as  "board \n掲示板"{
  + id [PK]
  --
  user_id[ユーザーID][FK]
  topic[トピック]
  description[説明]

}
entity posts as  "posts \n投稿"{
  + id [PK]
  --
  user_id [ユーザーID][FK]
  board_id[掲示板ID][FK]
  contents[コンテンツ]
  insert_at[登録日]
  update_at[更新日]

}
entity comments as  "comments \nコメント"{
  + id [PK]
  --
  user_id[ユーザーID][FK]
  post_id[投稿ID][FK]
  contents[コンテンツ]
  insert_at[登録日]
  update_at[更新日]

}
@enduml