spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kakeibo
    username: postgres
    password: postgres
  
# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
